# Generated by Django 3.0.3 on 2020-04-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocole1', '0006_experiment_limit_ideas_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experimentgroups',
            unique_together={('experiment', 'group')},
        ),
    ]
